apiVersion: v1
kind: Service
metadata:
  name: fivegc-service
  labels:
    app: fivegc-service
spec:
  type: ClusterIP
  selector:
    app: fivegc-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9008
