apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-tracing-service
  labels:
    app: distributed-tracing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-tracing-service
  template:
    metadata:
      labels:
        app: distributed-tracing-service
    spec:
      containers:
        - name: distributed-tracing-service
          image: distributed-tracing-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9005
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
