server:
  port: 9005
  shutdown: graceful

spring:
  application:
    name: distributed-tracing-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    url: ${TRACING_DB_URL:jdbc:postgresql://localhost:5435/tracing_db}
    username: ${TRACING_DB_USERNAME:tracing}
    password: ${TRACING_DB_PASSWORD:tracing}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{trace_id:-N/A}] [%X{span_id:-N/A}] %-5level %logger{36} - %msg%n"
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://tracing-postgres:5432/tracing_db
    username: tracing
    password: tracing
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
