services:
  eureka-server:
    build: ../spring-cloud/eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

  auth-service:
    build: ../microservices/auth-service
    mem_limit: 512m
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
    depends_on:
      - eureka-server
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

  gateway-service:
    build: ../spring-cloud/gateway-service
    mem_limit: 512m
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_TOOL_OPTIONS="-javaagent:/application/BOOT-INF/lib/opentelemetry-javaagent-2.13.3.jar" #maven will place jar in BOOT-INF as per dep mentioned in pom. This will instruct the JVM to run the OpenTelemetry Java agent from the path.
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_METRIC_EXPORT_INTERVAL=15000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
    depends_on:
      - eureka-server
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge