apiVersion: v1
kind: Service
metadata:
  name: fault-injection-service
  labels:
    app: fault-injection-service
spec:
  type: ClusterIP
  selector:
    app: fault-injection-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9006
